// "use client"

import "./globals.css";
import StoreProvider from "../redux/storeProvider";
import { AuthWrapper } from '@/app/components/auth-wrapper';
import { Metadata } from "next";
import { geistMono, geistSans } from "@/fonts";
import Footer from "./components/footer";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{children: React.ReactNode;}>) {


  return (
    <StoreProvider>
      <html lang="en" data-theme="retro" >
        <AuthWrapper>
          <body data-theme="retro" 
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
              <div className="mb-auto flex-grow">
              {children}
              </div>
            <Footer/>
          </body>
        </AuthWrapper>
      </html>
    </StoreProvider>
  );
}
